spring.application.name=inventory-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=services_user
spring.datasource.password=services_user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
